In [15]:
import numpy as np
from random import randint
import sys
sys.path.append("..")
from solvers.aco.aco_solver import AntColonyOptSolver
from problem.sudoku_manager import Sudoku, generate_boards

In [16]:
sud = Sudoku('hard', randint(0, 49))

In [17]:
print(sud.board)

[[7 6 9 0 5 0 0 4 0]
 [0 0 1 4 0 0 0 0 0]
 [8 4 2 0 0 0 0 0 5]
 [1 0 3 0 0 8 0 7 0]
 [9 0 0 6 0 2 0 0 0]
 [0 0 0 1 0 0 0 8 0]
 [2 0 0 0 0 5 6 0 0]
 [0 3 0 0 0 0 7 0 0]
 [0 0 0 8 0 0 0 1 0]]


In [18]:
print(sud.fixed_count)

27


In [19]:
print(sud.state)

{(0, 3): {2, 3}, (0, 5): {1, 3}, (0, 6): {1, 2, 3, 8}, (0, 8): {1, 2, 3, 8}, (1, 0): {3, 5}, (1, 1): {2, 5}, (1, 4): {2, 3, 6, 7, 8, 9}, (1, 5): {3, 6, 7, 9}, (1, 6): {2, 3, 8, 9}, (1, 7): {2, 3, 6, 9}, (1, 8): {2, 3, 6, 7, 8, 9}, (2, 2): {2}, (2, 3): {3, 7, 9}, (2, 4): {1, 3, 6, 7, 9}, (2, 5): {1, 3, 6, 7, 9}, (2, 6): {1, 3, 9}, (2, 7): {3, 6, 9}, (3, 1): {2, 5}, (3, 3): {5, 9}, (3, 4): {4, 9}, (3, 6): {2, 4, 5, 9}, (3, 8): {2, 4, 6, 9}, (4, 1): {5, 7, 8}, (4, 2): {4, 5, 7, 8}, (4, 4): {3, 4, 7}, (4, 6): {1, 3, 4, 5}, (4, 7): {3, 5}, (4, 8): {1, 3, 4}, (5, 0): {4, 5, 6}, (5, 1): {2, 5, 7}, (5, 2): {4, 5, 6, 7}, (5, 4): {3, 4, 7, 9}, (5, 5): {3, 4, 7, 9}, (5, 6): {2, 3, 4, 5, 9}, (5, 8): {2, 3, 4, 6, 9}, (6, 1): {1, 7, 8, 9}, (6, 2): {4, 7, 8}, (6, 3): {3, 7, 9}, (6, 4): {1, 3, 4, 7, 9}, (6, 7): {3, 9}, (6, 8): {3, 4, 8, 9}, (7, 0): {4, 5, 6}, (7, 2): {4, 5, 6, 8}, (7, 3): {2, 9}, (7, 4): {1, 2, 4, 6, 9}, (7, 5): {1, 4, 6, 9}, (7, 7): {2, 5, 9}, (7, 8): {2, 4, 8, 9}, (8, 0): {4, 5, 6},

In [20]:
solver = AntColonyOptSolver()

In [21]:
solver.solve(sudoku=sud)

array([[7, 6, 9, 2, 5, 1, 8, 4, 3],
       [3, 5, 1, 4, 8, 9, 2, 6, 7],
       [8, 4, 2, 3, 6, 7, 1, 9, 5],
       [1, 2, 3, 5, 9, 8, 4, 7, 6],
       [9, 8, 4, 6, 7, 2, 3, 5, 1],
       [5, 7, 6, 1, 3, 4, 9, 8, 2],
       [2, 1, 8, 7, 4, 5, 6, 3, 9],
       [4, 3, 5, 9, 1, 6, 7, 2, 8],
       [6, 9, 7, 8, 2, 3, 5, 1, 4]])