In [1]:
import sys

sys.path.append("..")
from solvers.ga.ga_solver import GeneticAlgorithmSolver
from problem.sudoku import Sudoku
from problem.sudoku_manager import SudokuManager

In [2]:
sm = SudokuManager()

ss = sm.load_n_level_boards("medium", 10)

sud = Sudoku(ss[3])

ga_solver = GeneticAlgorithmSolver(sud, 400, 6)

In [3]:
print(sud.board)
chr = ga_solver.generate_chrom()
print(chr)
print(sud.board)
print(ga_solver.sudoku.board)

[[4 0 0 0 8 5 6 0 0]
 [0 0 0 1 3 0 0 2 0]
 [0 2 0 9 0 0 8 1 0]
 [1 0 0 0 0 0 0 7 0]
 [0 0 5 0 0 1 0 0 0]
 [0 4 6 0 0 0 0 8 0]
 [0 0 9 7 6 0 0 0 0]
 [0 0 8 5 0 0 0 9 0]
 [0 0 0 8 0 0 0 0 1]]
[[4 3 2 7 8 5 6 9 1]
 [7 8 6 1 3 9 5 2 4]
 [7 2 6 9 3 5 8 1 4]
 [1 2 4 6 5 9 8 7 3]
 [2 9 5 3 7 1 4 6 8]
 [9 4 6 3 1 2 5 8 7]
 [3 8 9 7 6 4 5 2 1]
 [3 6 8 5 7 2 1 9 4]
 [4 2 7 8 3 6 5 9 1]]
[[4 0 0 0 8 5 6 0 0]
 [0 0 0 1 3 0 0 2 0]
 [0 2 0 9 0 0 8 1 0]
 [1 0 0 0 0 0 0 7 0]
 [0 0 5 0 0 1 0 0 0]
 [0 4 6 0 0 0 0 8 0]
 [0 0 9 7 6 0 0 0 0]
 [0 0 8 5 0 0 0 9 0]
 [0 0 0 8 0 0 0 0 1]]
[[4 0 0 0 8 5 6 0 0]
 [0 0 0 1 3 0 0 2 0]
 [0 2 0 9 0 0 8 1 0]
 [1 0 0 0 0 0 0 7 0]
 [0 0 5 0 0 1 0 0 0]
 [0 4 6 0 0 0 0 8 0]
 [0 0 9 7 6 0 0 0 0]
 [0 0 8 5 0 0 0 9 0]
 [0 0 0 8 0 0 0 0 1]]


In [4]:
population = ga_solver.generate_population()

In [5]:
print(population)

[array([[4, 9, 2, 7, 8, 5, 6, 3, 1],
       [4, 6, 5, 1, 3, 8, 9, 2, 7],
       [4, 2, 5, 9, 3, 6, 8, 1, 7],
       [1, 2, 8, 6, 5, 9, 3, 7, 4],
       [6, 7, 5, 8, 4, 1, 3, 9, 2],
       [7, 4, 6, 1, 2, 5, 3, 8, 9],
       [4, 5, 9, 7, 6, 1, 2, 8, 3],
       [7, 3, 8, 5, 6, 4, 2, 9, 1],
       [6, 9, 4, 8, 3, 2, 7, 5, 1]]), array([[4, 9, 1, 7, 8, 5, 6, 3, 2],
       [5, 4, 6, 1, 3, 9, 8, 2, 7],
       [5, 2, 6, 9, 3, 4, 8, 1, 7],
       [1, 8, 2, 3, 6, 5, 9, 7, 4],
       [3, 4, 5, 8, 2, 1, 7, 9, 6],
       [7, 4, 6, 9, 1, 2, 5, 8, 3],
       [2, 5, 9, 7, 6, 1, 3, 4, 8],
       [7, 1, 8, 5, 2, 4, 3, 9, 6],
       [2, 3, 7, 8, 6, 4, 9, 5, 1]]), array([[4, 1, 7, 9, 8, 5, 6, 2, 3],
       [8, 5, 6, 1, 3, 4, 7, 2, 9],
       [6, 2, 7, 9, 5, 4, 8, 1, 3],
       [1, 6, 5, 3, 2, 4, 8, 7, 9],
       [3, 7, 5, 4, 6, 1, 9, 2, 8],
       [9, 4, 6, 2, 1, 5, 7, 8, 3],
       [3, 5, 9, 7, 6, 2, 4, 1, 8],
       [1, 6, 8, 5, 7, 4, 2, 9, 3],
       [3, 5, 2, 8, 7, 4, 9, 6, 1]]), array([[4, 1, 9, 3, 8

In [6]:
chr.T

array([[4, 7, 7, 1, 2, 9, 3, 3, 4],
       [3, 8, 2, 2, 9, 4, 8, 6, 2],
       [2, 6, 6, 4, 5, 6, 9, 8, 7],
       [7, 1, 9, 6, 3, 3, 7, 5, 8],
       [8, 3, 3, 5, 7, 1, 6, 7, 3],
       [5, 9, 5, 9, 1, 2, 4, 2, 6],
       [6, 5, 8, 8, 4, 5, 5, 1, 5],
       [9, 2, 1, 7, 6, 8, 2, 9, 9],
       [1, 4, 4, 3, 8, 7, 1, 4, 1]])

In [7]:
chr

array([[4, 3, 2, 7, 8, 5, 6, 9, 1],
       [7, 8, 6, 1, 3, 9, 5, 2, 4],
       [7, 2, 6, 9, 3, 5, 8, 1, 4],
       [1, 2, 4, 6, 5, 9, 8, 7, 3],
       [2, 9, 5, 3, 7, 1, 4, 6, 8],
       [9, 4, 6, 3, 1, 2, 5, 8, 7],
       [3, 8, 9, 7, 6, 4, 5, 2, 1],
       [3, 6, 8, 5, 7, 2, 1, 9, 4],
       [4, 2, 7, 8, 3, 6, 5, 9, 1]])

In [8]:
import numpy as np
test_chr = np.ones((9, 9))
test_chr[0, 5] = 0
test_chr[0, 4] = 0

SyntaxError: invalid syntax (815426033.py, line 2)

In [ ]:
ev = ga_solver.evaluate_chrom(test_chr)
print(ev)

32


In [ ]:
sudoku_mild = np.array([0,3,0,0,7,0,0,5,0,5,0,0,1,0,6,0,0,9,0,0,1,0,0,0,4,0,0,0,9,0,0,5,0,0,6,0,6,0,0,4,0,2,0,0,7,0,4,0,0,1,0,0,3,0,0,0,2,0,0,0,8,0,0,9,0,0,3,0,5,0,0,2,0,1,0,0,2,0,0,7,0])
sudoku_mild = sudoku_mild.reshape(9,9)
sudoku_mild = Sudoku(sudoku_mild)

array([[0, 3, 0, 0, 7, 0, 0, 5, 0],
       [5, 0, 0, 1, 0, 6, 0, 0, 9],
       [0, 0, 1, 0, 0, 0, 4, 0, 0],
       [0, 9, 0, 0, 5, 0, 0, 6, 0],
       [6, 0, 0, 4, 0, 2, 0, 0, 7],
       [0, 4, 0, 0, 1, 0, 0, 3, 0],
       [0, 0, 2, 0, 0, 0, 8, 0, 0],
       [9, 0, 0, 3, 0, 5, 0, 0, 2],
       [0, 1, 0, 0, 2, 0, 0, 7, 0]])

In [ ]:
new_solver = GeneticAlgorithmSolver(sudoku_mild,, pop_size=5000, chrom_size=12, pc=0.8, pm=0.1, t_max=800)
sudoku_mild.board

array([[7, 2, 0, 3, 0, 4, 0, 0, 0],
       [8, 0, 4, 1, 0, 0, 2, 3, 0],
       [0, 6, 0, 8, 0, 0, 1, 0, 0],
       [0, 3, 0, 0, 8, 9, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 2],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 9, 0, 0, 6, 0, 0],
       [3, 0, 8, 5, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 2, 0]])

In [ ]:
results = new_solver.solve()

I: 0 best: 194 max: 194
Improvement! Score: 196
I: 1 best: 196 max: 196
Improvement! Score: 197
I: 2 best: 197 max: 197
I: 3 best: 197 max: 193
I: 4 best: 197 max: 196
Improvement! Score: 205
I: 5 best: 205 max: 205
I: 6 best: 205 max: 200
I: 7 best: 205 max: 199
I: 8 best: 205 max: 198
I: 9 best: 205 max: 201
I: 10 best: 205 max: 200
I: 11 best: 205 max: 199
I: 12 best: 205 max: 200
Improvement! Score: 206
I: 13 best: 206 max: 206
I: 14 best: 206 max: 203
I: 15 best: 206 max: 202
I: 16 best: 206 max: 205
I: 17 best: 206 max: 203
I: 18 best: 206 max: 203
I: 19 best: 206 max: 206
I: 20 best: 206 max: 203
I: 21 best: 206 max: 203
Improvement! Score: 207
I: 22 best: 207 max: 207
I: 23 best: 207 max: 206
I: 24 best: 207 max: 204
I: 25 best: 207 max: 207
I: 26 best: 207 max: 207
Improvement! Score: 209
I: 27 best: 209 max: 209
I: 28 best: 209 max: 208
I: 29 best: 209 max: 209
Improvement! Score: 210
I: 30 best: 210 max: 210
I: 31 best: 210 max: 210
Improvement! Score: 211
I: 32 best: 211 ma

In [ ]:
best_chrom, score_best_global, best_per_iter = results

In [ ]:
best_chrom

array([[7, 2, 1, 3, 9, 4, 5, 6, 8],
       [8, 9, 4, 1, 6, 5, 2, 3, 7],
       [5, 6, 3, 8, 2, 7, 1, 9, 4],
       [1, 3, 2, 4, 8, 9, 5, 7, 6],
       [9, 8, 7, 6, 5, 1, 3, 4, 2],
       [4, 5, 6, 2, 3, 7, 9, 8, 1],
       [2, 7, 5, 9, 4, 8, 6, 1, 3],
       [3, 1, 8, 5, 7, 2, 4, 6, 9],
       [6, 4, 9, 7, 1, 3, 8, 2, 5]])